### ISSUE TITLE
Regridding currently crashes

### ISSUE THREAD

**Issue by markpayneatwork** [Klimaatlas/KAPy#11]
Regridding is currently performed using the xesmf package - however, this simply crashes in a rather non-graceful manner when used in bulk. It's hard to know why, but we need to find an alternative approach e.g.
* CDO (in Python)
* Others?

**Comment by markpayneatwork** [comment]
@ShingiNangombe Here is some of the documentation for the python implementation of CDO: https://code.mpimet.mpg.de/projects/cdo/wiki/Cdo%7Brbpy%7D Could be a good place to start. It looks fairly straightforward, but....

**Comment by ShingiNangombe** [comment]
@markpayneatwork 
I didnt know how  missed a notification of this comment. Yah, the regridding methods of cdo can be used in python as a slave sort of. Nonetheless, the regridding using the python xesmf package worked when I tested with 3 different Euro Cordex data over Denmark. Maybe we can a discussion on this.

**Comment by markpayneatwork** [comment]
Part of the solution to this problem is also a more general approach to handling coordinate systems. Some tricky cases:
* Model is on rlon, rlat grid, but we want to subset by lon, lat, which are stored as variables rather than coordinates
* Model coordinates are 'longitude' rather than 'lon', or vice versa.
* Convention may change between data sources e.g. ERA5 vs CORDEX

**Comment by markpayneatwork** [comment]
Here's what I know. Regridding using the xesmf engine
* works fine when the code is run in a debugging or stand-alone mode
* exits cleanly from the script when run inside the snakemake task
* but crashes when finishing the snakemake task. Snakemake therefore deletes the (otherwise fine) output file
* The crash is related to running the `xe.Regridder()` function - if this line is disabled, then everything proceeds as normal.

This appears to be a bug with how xesmf cleans up its environments - given that xesmf points to an external library (I think), there may be something there. 

Getting this to work cleanly however is going to be hard, and creating a minimum working example will be a lot of effort, given the snakemake dependencies. In the meantime, I think it's a better solution to use cdo for regridding - see #91 We can always add support for xesmf back in the future if required.

**Comment by markpayneatwork** [comment]
Closing - #91 will add CDO support for regridding instead
