### ISSUE TITLE
Add polygon-based spatial averaging

### ISSUE THREAD

**Issue by markpayneatwork** [Klimaatlas/KAPy#12]
Should be able to define a set of polygons in the configuration file and use this as the basis for the areal statistics.

**Comment by ShingiNangombe** [comment]
I have been trying to incorporate this into the code I have but no luck yet. I get an error, something to do with the CORDEX grid when using salem for area averaging over a shapefile polygon. I have other ways I am trying to do for this area averaging.

**Comment by ShingiNangombe** [comment]
We will try the "regionmask" and "geopandas" python package to use shapefile(s) to maskout polygon(s) of interest for each timestep. We have difined and tested a function for the masking, then the area averaging based on the polygons can be done after. 
@markpayneatwork

**Comment by markpayneatwork** [comment]
First draft up and running using `regionmask` and `geopandas

**Comment by markpayneatwork** [comment]
Looks to be working well. Do need to check how well this works with shapefiles that are not on a lon-lat grid
