### ISSUE TITLE
Replacing R Graphing code with Python code

### ISSUE THREAD

**Issue by davidayikwei** [Klimaatlas/KAPy#25]
Before we get started, please confirm that:
* [X] you have checked the issue list for pre-existing feature requests, including those that have been closed already. If a similar feature request already exists, please comment there instead of opening a duplicate.

**Is your feature request related to a problem? Please describe.**
Using KAPy requires knowledge of R and you need to have R installed. It will be better if everything was in Python.

**Describe the solution you'd like**
Convert existing R code to Python.

**Describe alternatives you've considered**
Non

**Additional context**
Non

**Comment by markpayneatwork** [comment]
Duplicate of #20
