### ISSUE TITLE
Add bias correction support

### ISSUE THREAD

**Issue by markpayneatwork** [Klimaatlas/KAPy#58]
**Describe the solution you'd like**
We need to support multiple bias correction methods in KAPy.

**Additional context**
Start with simple mean-adjust and standardisation. Interface to xclim sda. Allow custom methods

**Comment by markpayneatwork** [comment]
Some specs
* Configuration, including method, should take place on a variable-by-variable basis
* Define the reference dataset and time period in the configuration
* Use mean-adjust as a starting point

**Comment by btschwertfeger** [comment]
What about the python-cmethods package? It's way faster than xclim, provides various scale and distribution based techniques for adjusting climate data and is also free and open source.

**Comment by markpayneatwork** [comment]
Thanks for the tip @btschwertfeger! The structure that I am aiming for here is that we should be able to have multiple bias-correction methods and packages that you can switch between, so the more the merrier!

@ShingiNangombe can you take a look at python-cmethods please?

**Comment by ShingiNangombe** [comment]
We conducted some tests and comparisons of the `cmethods` and `xclim` methods for bias adjustment. The `cmethods` approach performs the adjustments faster, but the `xclim` method provides more flexibility by allowing the use of different adjustment options, such as interpolation and extrapolation. The ideal solution would be to implement a switch that incorporates both methods in the code, allowing users to choose which method to use, as well as when and where to apply it.

**Comment by btschwertfeger** [comment]
> We conducted some tests and comparisons of the `cmethods` and `xclim` methods for bias adjustment. The `cmethods` approach performs the adjustments faster, but the `xclim` method provides more flexibility by allowing the use of different adjustment options, such as interpolation and extrapolation. The ideal solution would be to implement a switch that incorporates both methods in the code, allowing users to choose which method to use, as well as when and where to apply it.

For cmethods, where do you want to have extra- and interpolation?

Feel free to open an issue with suggestions an I'll have a look at it.

**Comment by ShingiNangombe** [comment]
For example, when using bias adjustment methods like `EmpiricalQuantileMapping` or `QuantileDeltaMapping`, you can specify the interpolation method e.g `linear`  or `nearest` as follows:

```
# Training the quantile mapping model with reference (obs) and historical (model) data
qdm = sdba.QuantileDeltaMapping.train(ref=obs_data, hist=model_data)

# Adjusting the simulated data with 'nearest' interpolation method
adjusted_data = qdm.adjust(sim=model_sim, interpolation="nearest")
```
Using the `cmethods`, I did not see where one can specify this. Toggling between the two options doesn't show much difference in the output from the tests done using temperature data, but it will be nice to have the flexibility to do so.

**Comment by btschwertfeger** [comment]
I see. This will most probably not be supported in cmethods, as the implementations there are based on the underlying scientific research papers, formulas and optimized to work well for a more broader field of data sets. Adding such feature for interpolation - which to be honest, most users won't understand (nor willing to read the documentation), doesn't make a significant difference (as you said) and just bring complexity into the setup. 

What you can do instead is using hidden parameters, e.g. `global_max` and `global_min` (https://github.com/btschwertfeger/python-cmethods/blob/v2.3.0/cmethods/distribution.py#L221-L222) as well as the `max_scaling_factor` for multiplicative corrections (https://github.com/btschwertfeger/python-cmethods/blob/v2.3.0/cmethods/distribution.py#L260-L262), and something like this: https://github.com/btschwertfeger/python-cmethods/blob/v2.3.0/cmethods/distribution.py#L75-L76. 

These settings are hidden (and not documented) - to not bring the attention of users to think about it. You can play with those, but in 99 % of the cases, they're not making any difference. It also makes it hard to explain how the data was created and modified when using custom interpolation.

**Comment by markpayneatwork** [comment]
Implemented and closing. See also #115 for addition of `cmethods` methods
