### ISSUE TITLE
Validation of configuration options

### ISSUE THREAD

**Issue by markpayneatwork** [Klimaatlas/KAPy#59]
**Describe the solution you'd like**
Our `config.yaml` files should be validated before use, to catch the most basic errors

**Describe alternatives you've considered**
JSON-schemas appear to be a good way forward, and are supported directly by Snakemake

**Comment by markpayneatwork** [comment]
The `jsonscheme2md` package is potentially very useful here to document configuration options

**Comment by ketilt** [comment]
Nice! Turning schemas into something more readable sounds very valuable. Schemas can be hard to read in raw form

**Comment by markpayneatwork** [comment]
Have a look at these links to look inside the sausage factory:
https://github.com/markpayneatwork/KAPy/blob/v0.3_restructure_to_snakemake_workflow/workflow/schemas/config.schema.yaml
https://github.com/markpayneatwork/KAPy/blob/v0.3_restructure_to_snakemake_workflow/docs/configuration/config.md
